### ISSUE TITLE
Adressevask: Undersøg fuzzy match

### ISSUE THREAD

**Issue by baffioso** [baffioso/baffioso.github.io#14]
@katnegermis jeg har kigget lidt på dit [link](http://dawa.aws.dk/datavask/adresser?betegnelse=jernbane%20alle) og DAWA's dokumentation, for at se om jeg kunne blive lidt klogere på servicen. DAWA skriver:

> For kategori A og B gælder, at der kun returneres én adresse. For kategori C kan der returneres flere adresser.

Derudover kan jeg se at servicen returnerer `resultater[i].vaskeresultat.afstand`, som jeg går ud fra er et tal på hvor god matchen er. Jeg troede at DAWA listede resultater for kategori C, så det bedste match kom først, men det er ikke tilfældet i din jernbane-alle-søgning (hvis ellers min antagelse om `resultater.vaskeresultat.afstand` er rigtig). Her har `resultater[0]` afstand: 15 og `resultater[1]` afstand: 13.

Grunden til jeg ikke looper resultaterne fra første kald i [linie 66](https://github.com/baffioso/baffioso.github.io/blob/master/adressevask/js/main.js#L66) er, at jeg kun ønsker et bruge ét af DAWA's adressematch for hver adresse i CSV-filen. Derfor bruges indeks 0 ud fra ovenstående betragtning.

Ville det være en idé at lede efter laveste værdi i `resultater[i].vaskeresultat.afstand` for alle med kategori C og bruge det i kaldet på linie 66?

Er stadig meget ny i JavaScript, så beklager hvis jeg ikke er helt skarp i mine formuleringer.

**Comment by micvbang** [comment]
Hej @baffioso,

Jeg har givet et bud på: https://github.com/baffioso/baffioso.github.io/pull/15.

Michael

**Comment by baffioso** [comment]
GeoJSON output får ikke de forskellige attributter med hvor DAWA returnerer flere adresseforslag adresse. [https://github.com/baffioso/baffioso.github.io/blob/master/adressevask/js/main.js#L114-L125](L114-125)

**Comment by baffioso** [comment]
Hej @katnegermis
Jeg har nu kommenteret dine tilføjelser til koden [her](https://github.com/baffioso/baffioso.github.io/blob/master/adressevask/js/main.js#L65-L78). Hvis du har tid, må du gerne se om mine kommentarer giver mening.
Vh. Anders

**Comment by micvbang** [comment]
Hej @baffioso,

Det ser rimelig fornuftigt ud :)

**Comment by baffioso** [comment]
@katnegermis Tak for hjælpen
