### ISSUE TITLE
Adressevask: Lad bruger vælge attributter fra DAWA i GeoJSON output 

### ISSUE THREAD

**Issue by baffioso** [baffioso/baffioso.github.io#16]
Hej @kjoller 
Jeg har lavet en ny branch [iss16](https://github.com/baffioso/baffioso.github.io/tree/iss16), hvor jeg arbejder på at få lavet checkboxe som styrer hvilke DAWA-attributter, som kommer med i GeoJSON. 

![skaermbillede 2016-04-11 kl 21 49 51](https://cloud.githubusercontent.com/assets/7534153/14440287/7ab8e084-002f-11e6-8769-487cbcd8f1b2.png)

Min første tanke var at bruge jQuery til at finde ud af hvilke checkboxe som ikke er markeret. Den oplysning vil jeg bruge til at loope i gennem output array'et (som indeholder alle oplysningerne) og slette de properties, som brugeren ikke ønsker at have med i GeoJSON.

Ved du har rodet en del med checkboxe i forbindelse med CartoDB filteret, så ville høre om du har nogle inputs. 

Vh. Anders

**Comment by kjoller** [comment]
Mit første forsøg gik på at have en række checkboxe med tilknyttede labels. Så kunne man bruge jQuery til at iterere over checkboxe, og se om labels passede til den tekst man gerne ville vælge (det var dynamisk genererede værdier, så man kunne ikke rigtigt hardcode navne direkte i <input>-elementet).

Det virker fint langt hen ad vejen, men rent praktisk gav det problemer hvis man oversatte null-værdier til at hedde "intet", og nogen så tilføjede en kategori i data der hed 'intet'.

I mit tilfælde holder jeg valgmulighederne som objekter i et array i modellen, og hver gang man klikker på en checkbox, opdaterer jeg en 'selected'-attribut til true eller false, hvorefter jeg gentegner alle checkboxene for at være sikker på at selected-værdien og checkboxen aldrig kommer ud af sync.

Jeg kan ikke helt lure om den tilgang er overkill til din relativt overskuelige liste af på forhånd kendte værdier.

**Comment by baffioso** [comment]
Med dine råd har jeg nu fået det delvist til at spille - så jeg takker.

Jeg kommer til at hårdkode det, da det netop er begrænset hvormeget der skal tages med fra DAWA. Jeg har lavet det sådan, at der undersøges hvilke tjekbokse, som er vinget af når der trykkes på download knappen. Herefter slettes de attributter som ikke ønskes, hvorefter download dialogen bliver vist.

Jeg roder med at lave kopi af output arrayet, så properties kun bliver slettet i kopien. Tanken er at brugeren derved kan gemme forskellige versioner af outputtet, uden at properties bliver slettet fra originalen og derved ikke kan gendannes i alternativ version. Har endnu ikke fået det til at spille, men det kommer nok!

Hils på kontoret

**Comment by baffioso** [comment]
#17
